In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df=pd.read_csv("iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

The Naïve Bayes classifier is a supervised machine learning algorithm, which is used for classification tasks, like text classification. 
Some popular examples of Naïve Bayes Algorithm are spam filtration, Sentimental analysis, and classifying articles.


In [3]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [4]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['species']=le.fit_transform(df['species'])
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [5]:
y=df['species']
x=df.drop('species',axis=1)

In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)


In [7]:
from sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB()
gaussian.fit(xtrain,ytrain)

GaussianNB()

In [8]:
ypred = gaussian.predict(xtest) 

In [9]:
df = pd.DataFrame({'Real Values':ytest, 'Predicted Values':ypred})
df.head()

Real Values  Predicted Values
7             0                 0
56            1                 1
90            1                 1
29            0                 0
47            0                 0

In [10]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
print("Accuracy = "+str(accuracy_score(ytest,ypred)))
print("Error Rate = "+str(1-accuracy_score(ytest,ypred)))
print("Precision = "+str(precision_score(ytest,ypred,average='micro')))
print("Recall = "+str(recall_score(ytest,ypred,average='micro')))
cm=confusion_matrix(ytest,ypred)
print(cm)

Accuracy = 0.9333333333333333
Error Rate = 0.06666666666666665
Precision = 0.9333333333333333
Recall = 0.9333333333333333
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


Accuracy gives an overall assessment of how well the model performs across all classes.

Precision, on the other hand, focuses on the quality of positive predictions made by the model. 
The recall is the ratio tp / (tp + fn) where tp is the number of true positives and fn the number of false negatives. The recall is intuitively the ability of the classifier to find all the positive samples.

The first row represents the true labels for the first class. In this case, there are 10 instances that belong to class 0, and the classifier correctly predicted all of them as class 0 (true negatives).

The second row represents the true labels for the second class. There are 9 instances that belong to class 1, and the classifier predicted all of them correctly as class 1 (true positives). However, there is one instance that actually belongs to class 1 but was misclassified as class 2 (false negative).

The third row represents the true labels for the third class. There are 9 instances that belong to class 2, and the classifier predicted all of them correctly as class 2 (true positives). However, there is one instance that actually belongs to class 2 but was misclassified as class 1 (false negative).

In summary, the confusion matrix indicates that the classifier achieved perfect accuracy for class 0 (10 true negatives), but there was a misclassification in the second and third classes, resulting in one false negative each.